server:
  port: 8081

spring:
  profiles:
    active: @profiles.active@
  application:
    name: data-platform-masterdata

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

masterdata:
  vendor-config:
    cache-ttl-seconds: 300

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) [%X{traceId}] - %msg%n"
