server:
  port: 8888

spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) [%X{traceId}] - %msg%n"
