server:
  port: 8084

spring:
  profiles:
    active: @profiles.active@
  application:
    name: data-platform-billing

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
