server:
  port: 8085

spring:
  profiles:
    active: @profiles.active@
  application:
    name: data-platform-governance

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) [%X{traceId}] - %msg%n"
