package com.dataplatform.plugin.spi;

public enum ErrorCategory {
    CONFIGURATION_ERROR,
    PLUGIN_NOT_READY,
    PLUGIN_VERSION_MISMATCH,
    REQUEST_BUILD_ERROR,
    AUTH_SECURITY_ERROR,
    TRANSPORT_TIMEOUT,
    TRANSPORT_CONNECTION_ERROR,
    TRANSPORT_HTTP_ERROR,
    RESPONSE_SECURITY_ERROR,
    RESPONSE_PARSE_ERROR,
    BUSINESS_REJECTED,
    CONTRACT_VIOLATION,
    PLUGIN_INTERNAL_ERROR
}
