spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        enabled: true
      config:
        enabled: false

spring.data.redis:
  host: localhost
  port: 6379
  password: redis_password
  database: 0

sa-token:
  token-name: Authorization
  timeout: 7200
  is-concurrent: true
  is-share: false
  token-style: uuid
  token-prefix: Bearer
