package com.dataplatform.access.connector.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration;
import com.dataplatform.access.connector.entity.ConnectorPluginActivation;
import java.time.LocalDateTime;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

class ConnectorPluginActivationMapperIntegrationTest {

    private final ApplicationContextRunner contextRunner = new ApplicationContextRunner()
            .withConfiguration(AutoConfigurations.of(
                    DataSourceAutoConfiguration.class,
                    MybatisPlusAutoConfiguration.class))
            .withPropertyValues(
                    "spring.datasource.url=jdbc:h2:mem:connector-activation;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                    "spring.datasource.username=sa",
                    "spring.datasource.password=")
            .withUserConfiguration(MapperConfiguration.class);

    @Test
    void updateByIdClearsSafeErrorColumnsWhenActivationRecovers() {
        contextRunner.run(context -> {
            assertThat(context).hasNotFailed();
            JdbcTemplate jdbcTemplate = new JdbcTemplate(context.getBean(DataSource.class));
            jdbcTemplate.execute("""
                    CREATE TABLE connector_plugin_activation (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        service_instance_id VARCHAR(128) NOT NULL,
                        plugin_id VARCHAR(128) NOT NULL,
                        plugin_version VARCHAR(64) NOT NULL,
                        artifact_sha256 VARCHAR(64),
                        host_version VARCHAR(64),
                        state VARCHAR(32) NOT NULL,
                        loaded_at TIMESTAMP,
                        last_heartbeat_at TIMESTAMP,
                        safe_error_code VARCHAR(128),
                        safe_error_digest VARCHAR(128),
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
                    )
                    """);

            ConnectorPluginActivationMapper mapper = context.getBean(ConnectorPluginActivationMapper.class);
            ConnectorPluginActivation activation = failedActivation();
            assertThat(mapper.insert(activation)).isEqualTo(1);

            activation.setState("READY");
            activation.setSafeErrorCode(null);
            activation.setSafeErrorDigest(null);
            activation.setUpdatedAt(LocalDateTime.now());
            assertThat(mapper.updateById(activation)).isEqualTo(1);

            assertThat(jdbcTemplate.queryForObject(
                    "SELECT safe_error_code FROM connector_plugin_activation WHERE id = ?",
                    String.class,
                    activation.getId())).isNull();
            assertThat(jdbcTemplate.queryForObject(
                    "SELECT safe_error_digest FROM connector_plugin_activation WHERE id = ?",
                    String.class,
                    activation.getId())).isNull();
            assertThat(jdbcTemplate.queryForObject(
                    "SELECT state FROM connector_plugin_activation WHERE id = ?",
                    String.class,
                    activation.getId())).isEqualTo("READY");
        });
    }

    private ConnectorPluginActivation failedActivation() {
        LocalDateTime now = LocalDateTime.now();
        ConnectorPluginActivation activation = new ConnectorPluginActivation();
        activation.setServiceInstanceId("access-1");
        activation.setPluginId("demo");
        activation.setPluginVersion("1.0.0");
        activation.setArtifactSha256("a".repeat(64));
        activation.setHostVersion("test-host");
        activation.setState("FAILED");
        activation.setLastHeartbeatAt(now);
        activation.setSafeErrorCode("ILLEGALSTATEEXCEPTION");
        activation.setSafeErrorDigest("b".repeat(64));
        activation.setCreatedAt(now);
        activation.setUpdatedAt(now);
        return activation;
    }

    @Configuration(proxyBeanMethods = false)
    @MapperScan(basePackageClasses = ConnectorPluginActivationMapper.class)
    static class MapperConfiguration {
    }
}
