apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dmh-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dmh-deployer
subjects:
  - kind: ServiceAccount
    name: dmh-deployer
