global:
  environment: staging
  springProfile: staging
  nacosNamespace: staging
  nacosGroup: DMH_STAGING_LOCAL
components:
  gateway: {replicas: 2}
  masterdata: {replicas: 2}
  access: {replicas: 2}
  billing: {replicas: 2}
  identity: {replicas: 2}
  governance: {replicas: 2}
  web: {replicas: 2}
access:
  partition: 1
