package com.dataplatform.masterdata.connector.service;

/** Stable, value-free reason codes for migration inventory and later API projection. */
public enum LegacyHttpConversionReasonCode {
    EMPTY_PIPELINE,
    TOO_MANY_STEPS,
    NULL_STEP,
    STAGE_KEY_MISSING,
    DUPLICATE_STAGE_KEY,
    ORDER_MISSING_OR_INVALID,
    DUPLICATE_ORDER,
    CAPABILITY_UNSUPPORTED,
    PLUGIN_BINDING_MISSING,
    NON_LEGACY_PLUGIN,
    LEGACY_VERSION_UNSUPPORTED,
    TRANSPORT_COUNT_INVALID,
    CAPABILITY_ORDER_INVALID,
    DUPLICATE_ENABLED_CAPABILITY,
    REQUEST_BUILDER_MISSING,
    RESPONSE_PARSER_MISSING,
    RESPONSE_NORMALIZER_MISSING,
    UNKNOWN_CONFIG_FIELD,
    CONFIG_VALUE_UNSUPPORTED,
    REQUEST_ENDPOINT_MISSING,
    SECRET_REFERENCE_REQUIRED,
    PLATFORM_POLICY_REQUIRED,
    PLATFORM_TIMEOUT_MISMATCH,
    IDEMPOTENCY_SEMANTICS_UNSUPPORTED,
    RESPONSE_LIMIT_UNSUPPORTED
}
