-- Roll the initial installation back to an empty application schema.
-- DATABASECHANGELOG and DATABASECHANGELOGLOCK are intentionally retained so
-- Liquibase can finish recording the rollback and later re-apply the baseline.
DROP TABLE IF EXISTS
    billing_daily_event,
    billing_daily,
    billing_event,
    billing_usage_balance,
    billing_plan_tier,
    billing_plan,
    billing_template,
    billing_reconciliation,
    vendor_interface_security_version,
    vendor_interface_security_step,
    interface_param,
    api_key_interface,
    user_caller,
    role_permission,
    permission,
    user_role,
    role_info,
    user_info,
    encryption_key,
    service_health_check,
    quality_score,
    quality_rule,
    data_lineage,
    operation_log,
    circuit_breaker,
    alert_record,
    alert_rule,
    gray_rule,
    call_record,
    call_scene,
    api_key_product,
    api_key,
    caller_product,
    caller_info,
    vendor_config_extended,
    vendor_config,
    api_interface,
    data_type,
    vendor_info,
    tenant_info
CASCADE;
